name:                InterestTracker
version:             0.1.0.0
github:              "yourfin/InterestTracker"
license:             BSD3
author:              "YourFin"
maintainer:          "d.junkpobox+git@gmail.com"
copyright:           "YourFin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yourfin/InterestTracker#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- lens-aeson
- servant-server
- wai
- warp
- polysemy
- polysemy-plugin
- lens
- containers
- sqlite-simple
- time
- optparse-applicative
- modern-uri
- req
- text
- bytestring
- uri-encode
- quickcheck-instances

ghc-options: -O2 -flate-specialise -fspecialise-aggressively
default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - OverloadedStrings
  - MultiWayIf
  - LambdaCase
  - TemplateHaskell
  - QuasiQuotes
  - DeriveGeneric

library:
  source-dirs: src

executables:
  InterestTracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - InterestTracker

tests:
  InterestTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - InterestTracker
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - QuickCheck
    - generic-random
    - splitmix
    - random
